networks:
  laravel:
    driver: bridge

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686" # Jaeger UI
      - "5778:5778" # Configuration service
      - "14268:14268" # Thrift HTTP POST
      - "14250:14250" # gRPC
      - "4317:4317" # OpenTelemetry gRPC
      - "4318:4318" # OpenTelemetry HTTP
      - "9411:9411"
      - "6831:6831/udp"
      - "6832:6832/udp" 
    environment:
      - COLLECTOR_AUTH_ENABLED=false
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    logging:
      driver: "json-file"
      options:
        max-size: "10m" # 限制日誌大小
        max-file: "3" # 限制日誌文件數量
    networks:
      - laravel

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100" # Loki HTTP API
    networks:
      - laravel

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    ports:
      - "9080:9080" # Promtail HTTP API (可選)
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro # 掃描容器日誌
      - /var/run/docker.sock:/var/run/docker.sock:ro # 掛載 Docker 套接字
      - ./promtail-config.yml:/etc/promtail/config.yml # Promtail 配置
    command:
      - -config.file=/etc/promtail/config.yml
    networks:
      - laravel

  laravel_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_app:latest
    container_name: laravel_app
    ports:
      - "8100:8000"
    volumes:
      - .:/var/www/html
    networks:
      - laravel

  hotrod:
    image: jaegertracing/example-hotrod:latest
    container_name: hotrod
    environment:
      JAEGER_AGENT_HOST: jaeger
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
    ports:
      - "8084:8080" # HotROD service
    networks:
      - laravel