services:
  jaeger:
    image: jaegertracing/jaeger:2.2.0
    container_name: jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "5778:5778"
      - "9411:9411"

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: laravel_app:latest
  #   container_name: laravel_app
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - .:/var/www/html
  #   networks:
  #     - laravel
