server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  # 收集 Jaeger 容器的日誌
  - job_name: "jaeger"
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: ".*jaeger.*"  # 匹配容器名稱中包含 "jaeger" 的容器
        target_label: job
        replacement: "jaeger"  # 為匹配的容器賦予 job 名稱
      - source_labels: [__meta_docker_container_name]
        target_label: container
      - source_labels: [__meta_docker_labels_tag_key]
        target_label: http_status_code

  # 收集 Docker 容器的日誌
  - job_name: "docker_logs"
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: ".*"  # 匹配所有容器
        target_label: container
      - source_labels: [__meta_docker_container_name]
        regex: ".*"  # 為所有容器分配 job 名稱
        target_label: job
        replacement: "docker_logs"
